from config import settings

# URLS
PROTOCOL = "http"
DIALOG_SERVICE_URL = f"{PROTOCOL}://{settings.INTRATIME_SERVICE_NAME}:{settings.DIALOG_SERVICE_PORT}"
INTRATIME_SERVICE_URL = f"{PROTOCOL}://{settings.INTRATIME_SERVICE_NAME}:{settings.INTRATIME_SERVICE_PORT}"
USER_SERVICE_URL = f"{PROTOCOL}://{settings.USER_SERVICE_NAME}:{settings.USER_SERVICE_PORT}"
LOGGER_SERVICE_URL = f"{PROTOCOL}://{settings.LOGGER_SERVICE_NAME}:{settings.LOGGER_SERVICE_PORT}"
MONGO_DB_SERVER = f"mongodb://{settings.MONGO_DB_USER}:{settings.MONGO_DB_PASSWORD}@{settings.MONGO_DB_HOST}:"\
                  f"{settings.MONGO_DB_PORT}/"

# SLACK
SLACK_POST_MESSAGE_URL = 'https://slack.com/api/chat.postMessage'
SLACK_OPEN_DIALOG_URL = 'https://slack.com/api/dialog.open'

# DIALOG SERVICE
DIALOG_SERVICE_ECHO_REQUEST = f"{DIALOG_SERVICE_URL}/echo"

# USER SERVICE
USER_SERVICE_ECHO_REQUEST = f"{USER_SERVICE_URL}/echo"
USER_SERVICE_MANAGE_REQUEST = f"{USER_SERVICE_URL}/user"

# INTRATIME SERVICE
INTRATIME_SERVICE_ECHO_REQUEST = f"{INTRATIME_SERVICE_URL}/echo"
INTRATIME_SERVICE_CHECK_CREDENTIALS_REQUEST = f"{INTRATIME_SERVICE_URL}/check_user_credentials"
INTRATIME_SERVICE_REGISTER_REQUEST = f"{INTRATIME_SERVICE_URL}/register"

# LOGGER SERVICE
LOGGER_SERVICE_ECHO_REQUEST = f"{LOGGER_SERVICE_URL}/echo"
LOGGER_SERVICE_POST_LOG_REQUEST = f"{LOGGER_SERVICE_URL}/log"

# JSON FORMATS
MESSAGE_FIELD = 'message'
