version: '3'

services:

    mongo-service:
      image: mongo:4.0
      volumes:
        - ./deploy/db_data:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD

    mongo-express:
      image: mongo-express
      ports:
        - 8081:8081
      environment:
        - ME_CONFIG_MONGODB_SERVER
        - ME_CONFIG_BASICAUTH_USERNAME
        - ME_CONFIG_BASICAUTH_PASSWORD
        - ME_CONFIG_MONGODB_ADMINUSERNAME
        - ME_CONFIG_MONGODB_ADMINPASSWORD
      depends_on:
        - mongo-service

    dialog-service:
      build:
        # Set workdir to current directory. Neccesary to the requirements file copy in Dockerfile
        context: .
        dockerfile: ./deploy/Dockerfile
      ports:
        - 3000:3000
      volumes:
        - ./src:/src
      environment:
        - SLACK_API_TOKEN
        - CIPHER_KEY
        - MONGO_DB_USER
        - MONGO_DB_PASSWORD
      working_dir: /src/services
      command: python3 dialog_service.py

    user-service:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      ports:
        - 3001:3001
      volumes:
        - ./src:/src
      environment:
        - SLACK_API_TOKEN
        - CIPHER_KEY
        - MONGO_DB_USER
        - MONGO_DB_PASSWORD
      working_dir: /src/services
      command: python3 user_service.py
      depends_on:
        - mongo-service

    intratime-service:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      ports:
        - 3002:3002
      volumes:
        - ./src:/src
      environment:
        - SLACK_API_TOKEN
        - CIPHER_KEY
        - MONGO_DB_USER
        - MONGO_DB_PASSWORD
      working_dir: /src/services
      command: python3 intratime_service.py

    logger-service:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      ports:
        - 3003:3003
      volumes:
        - ./src:/src
      environment:
        - SLACK_API_TOKEN
        - CIPHER_KEY
        - MONGO_DB_USER
        - MONGO_DB_PASSWORD
      working_dir: /src/services
      command: python3 log_service.py

    bot-service:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      volumes:
        - ./src:/src
      environment:
        - SLACK_API_TOKEN
        - CIPHER_KEY
        - MONGO_DB_USER
        - MONGO_DB_PASSWORD
      working_dir: /src/bot
      command: python3 reminder_bot.py