version: '3'

services:

  mongo-service:
    image: mongo:4.0
    volumes:
      - ./deploy/db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    image: mongo-express
    ports:
      - 10045:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    depends_on:
      - mongo-service

  intratime-bot:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - 10050:10050
    volumes:
      - ./:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    command: >
            bash -c "python3 setup.py install &&
                     python3 /app/src/intratime_slack_bot/services/slack_service.py"
    depends_on:
      - mongo-service
    links:
      - mongo-service
